apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: keycloak
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  sources:
    - repoURL: registry-1.docker.io/bitnamicharts
      chart: keycloak
      targetRevision: 24.7.3
      helm:
        valueFiles:
          - $values/resources/apps/keycloak/values.yaml
    - repoURL: https://github.com/JoseAle8Git/pr-ctica_keycloak_gitops.git
      targetRevision: HEAD
      ref: values
  destination:
    server: https://kubernetes.default.svc
    namespace: monitoring
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true