---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: keycloak-postgresql-secret
  namespace: monitoring
spec:
  encryptedData:
    postgres-password: AgANk1n+ksGTKilcpl9J8IA/FNKb935tydIyc2HpeKdB9/8VKA5HA6NUeUNcQmHORFv9iQ0x7n9VQbNjOyrQ54ANDritdXdLhVSroFDQUQ62y9FUPl/8muo0vj+OpswN9rFtfGuzfphCsTPdnhbkVxBU3k47yboGKDVHU4dcYDozi/99irsj0YvEvTEzOS+WraeFnhVdhvHKonAJm3XAllsqve9D9yf8RVZWws9x3FwgLWsh/WE4LTy7y1dCYQQtdPZOSPjVWKItKBAJBnjDPzu1NLTs95WUXXwP/S2NxLLno+l7mLE/77+xhyscFxuzyxD1CSgECEE2jb4xPXW0tynYlTP+trQmPK05qqnlFdY/iCnMEe1HKuWCZijEg/3BVGAqS63sDXdQ2Zep5oWOfuHW0wTNtVkOQlNiH0o1QfVym+tBg6R5tRrpBv1mppQVaas2YD5xmL1fIPThgMEA61ThqhbJ1wCbiCFrB/lkV2lRDBV3SVlLcf+uHxu+Hg6gtE76ik2ZWLI6QPS+zH3YpP56pNqAYv8uXq8NRj1aQtI5DmQ5IJT8ILmZnEEPeB1XOYKjP5QU/ixg14blHznz9P6Hi7rasenqjE29xJNuj0JHkDaL8vSp6x0+mJ78FDDDSWKMdc+oQBm96MauSdXBaErpON0jo2OhTPz3LFhMSf6Ds6ciPee23Dw3wsi32g2xzr1mXAt+psrzwYqkww==
    postgresql-password: AgCdOZ8pro4/QYbBI+p8pM2YMdoW1pKCn+/q/BLAQuivGMIIXv6Np9DgFvZdzMZ/6RXwkS5642IZ5lPB5ajoxSKOFmBdnx6NmMQvT6d4jX6rYuQ415UKa9SltHXA2B+0PQKAam4Q74Ya47O2FQlUKV/45KnLY2+svA6dBWxI018pxanD+rm7O4c7JX9v+goLzQsSgGVFaMrpi/93OzTJyszO6xpD9SiQcYTQlFpvJjXgUguU4CEI8zZhPUvBHWPJpqvsEk49ywc+iM+q1lSkwg1F1njPI2SABYtu4a8Ps3M0sWYNRjtqlmuOO5x/Lhf4PgwWXqabfY41O4veTYtoEa95VgTU9O7Dp2WJJY5YHQ2M6E0mtwPBKC4/pMbxZgk3HEO7JghGisbaX5fA6UzSHf/9ZB17Td31snrCix3TAoSVGjWS/Uk3fvBRFp37BVShJYfHO0q+0T6JXhTq7YCJfvQznxbaveifPUXuKK7f/stcju+tYSaBjChWjm41QC/Vklvy6uDOOo7oqiXEmIZmCmWCu6rse+BddXugpshaiFxQLT66zoX7m1uLIPRFyjCg/Bn0nDr8JS/0d2chvAcsxtcF+UXijEylpZKRAU0RCBpykAKI2KFPvEDr/SjTUx6vNa5nPcUdJqI6H5QCvk0bwYoFxUNAw88eWzg6S7hv8OyZl5ssjIhyk4+74RgsJ0l+GevBOuNhYdphFn3OCQ==
  template:
    metadata:
      name: keycloak-postgresql-secret
      namespace: monitoring
