---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: keycloak-postgresql-secret
  namespace: monitoring
spec:
  encryptedData:
    postgresql-password: AgBHIkstAQqFyYL6gMYo9Iwg9VYo2QdqqN4TqsI6wTbTiSB8jxnUODsnQBDZbtEu3+seEE8/SGl5NYKiStTM7KwIeNa4ZVycw7P7P2FcXxzjaMvmukBiDpHzpanMcIq2ASmf1DPVpnjdFjLdokbiCrgi0Ycv8SKvAps1dnuNYq2ZNWUS7ngvaDtNBLrcwCfnHwk4GaAXlPUJowto+FYblE4F5kHW089fDb1l3XsEQ8eut4yU4cYbS5o7swG3KmDWv69Oq5qrUVHEkrqep2uZcFvid7Dqjl5n4MYgtTl/iQ+221YMDeqlgGf1nC+BD+IQifKEA5tu6da4M4M4r9HSFZ6lWFoFD6Cgz8S9+XJ7syyeXXWD3yOGd14Exc1p4V7jsBAh1yzx51amdYfW7q87S+d62PyNkR2WcJhZIzbaI/hQLTX5Mfu/h0Q4N2k5lXmSX/xkFaZf/RE8ifuN4zaavdbIE/pCXMgl0DVFMjtS6Q/5w3ocbgXhFyORBDhKrTRqCOkRwnwlY4SFdstHc1FrHN/GZSTuuG9WExlzPH9o7YVlSqcNpcGeukCfOf9NQA39meEqkxpyzlGgzEgmxIx3NsDN0OJQsVGR2FYqvgotwqLTGlePDtBJn5SFYcoGmZu8AWTK0ujB5kuo2QVSuhQADR64Hy5JLn45FGftp2IT7RzRFmu5SVIvc57VjD5pUOUXJf+Q8vRXAmkUEy04cQ==
  template:
    metadata:
      name: keycloak-postgresql-secret
      namespace: monitoring
