---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: keycloak-admin-secret
  namespace: monitoring
spec:
  encryptedData:
    admin-password: AgCL5TvpxD/DOtzYESgC5ABO+3yJhZFgoccamJfSMQ6kcPWnBCWb0VjUNEEq+cSDngTc8vp0iE8wDfsgUH/XBVT86WbYtU1g+6nNmqXG8McrxSeMS+Gq9wYDR0+PNbUDaI/gcUPkeiEbIy+W+BsatEpbUz9iZ7fR3IsULUbb0A4X6St+GUJ6h9SptNqqWussbqIxsQ5UejdzJ7p0pLhtf19I2bEuysueR/fFeVGQyuk6BlI+lePpnH4z8UAXFdqyPIyFvD5yanrWYahYVnvi+hlAPsqZeaUVMwolmrTRR3YUE8tksJjbqu5QjiWwp8Br8oNRRR7jgR/LsDsSjHOV+bsodGsToXAc5OvPor6fGCEguo/L9XVidHIxeYNF+RT2E0DtVhItj568YmIZrIHEtEZvJyMELwnp0t57nShDb38Db3yBn6DdMJjkUuJU2CkNM7bJ7A5rAvuztmtQcutVj3mbpVDMoPZoXiaIyW95s6TXw43gFtXpeYC7By7i1F8uydGTbyrGbfUX/nZEMksdxVLdYBRDPioBvX71rmox6p1Os9+jCkeS/2rqKWIwrZ0Xo5wZvI+cvD3qegLLz1Y1CA+HPOB4wbJk9Stc+0GetfSLz6e/dk055fpZtYQipUQ8bz2UhrW6a6yy/rn18U3B8XA8i0+57ARjrv3LKHXj2y5WfJF/h/lg9ETUTk0HvycZdo4dc60K9I91aQ==
  template:
    metadata:
      name: keycloak-admin-secret
      namespace: monitoring
