---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: keycloak-admin-secret
  namespace: monitoring
spec:
  encryptedData:
    admin-password: AgDYPmFSwSsPBvXqzUUDZFlMO1BOO4ZSX5zQL/n1zj7YnMXk97nLTBS4g09PTz1t0vy039owXm4IiTPPcvzinTWhbBOwB32EDGdalBJCQSt+BjX/ey4+lhpT1z4B5jVES163j6Z10cqlQm3AufUdoUH9TbBIBXYJ9IVfHzTu+eCyhUpPiJ0bOjMYeTbI4FOpo8S5TDE55YGY+AhCN3ddb3IkXxNyLg9IOsl2ahruGDHZW8JHINOl1peENJPvjq69Jit7HZ0jhcOJe6XoO99tN5lo5bKn4LchWs1NiQ5dXA3AtG1066KKQsPsC7h+0ntCovC/iwGEN0py0HqcMJmyBsHGtrm1rRXHUIU4rED+IkEgbKg+ElJxmyzg6g8dNt9HNJH4gNbraG1g0An5oqtzk4Fde2zVZ8yo3qjw+ZU7xkDoLfvJFc2t7lVJVkPa6jY7OcL/PPpozED+8+thZYljTivFoHjpKxjYEurWmeP32X5z/crjo+KerB5PUIKyEMB4yukVgl/UEM9/+7Y4bJ0PGoeCsSe+0uiwCZx7ljTkzE+yh//yYxaxlia88OkzAhROPI/alY6yOfg6x+tmTYWXjm/0TYJzyf9GiPVYN/4SXyMeF4q2CBezQs/eTyNt4Ms9gnwbHd56oSEnSdcJV1pg+zUAVDCdaacPNOn5IZlLqjuBYLy1AnvDKbWCkIugCJFoAga7Yv4Db1PI7Q==
  template:
    metadata:
      name: keycloak-admin-secret
      namespace: monitoring
